---------------------------------------
--------------MINI PROJECT-------------
---------------------------------------

-- CREATE TABLE --

CREATE TABLE USER_SUBMISSIONS (
ID SERIAL PRIMARY KEY,
USER_ID BIGINT,
QUESTION_ID INT,
POINTS INT,
SUBMITTED_AT TIMESTAMP WITH TIME ZONE,
USERNAME VARCHAR(50)
);

SELECT * FROM USER_SUBMISSIONS;

---------------------------------------
-------------QUESTIONS-----------------
---------------------------------------

--Q1. List All Distinct Users and Their Stats. (user name, total submissions, and points earned)

SELECT USERNAME,
COUNT(ID) AS TOTAL_SUBMISSIONS,
SUM(POINTS) AS POINTS_EARNED
FROM USER_SUBMISSIONS
GROUP BY USERNAME
ORDER BY POINTS_EARNED DESC;

--Q2. Calculate the Daily Average Points for Each User.

SELECT
TO_CHAR(SUBMITTED_AT, 'MM-DD') AS DAY,
USERNAME,
AVG(POINTS) AS DAILY_AVERAGE_POINTS
FROM USER_SUBMISSIONS
GROUP BY 1,2
ORDER BY USERNAME;

--Q3. Find the Top 3 Users with the Most Correct Submissions for Each Day.

WITH DAILY_SUBMISSIONS AS (
SELECT USERNAME,
TO_CHAR(SUBMITTED_AT, 'DD-MM') AS DAILY,
SUM(CASE WHEN POINTS > 0 THEN 1 ELSE 0 END) AS CORRECT_SUBMISSIONS
FROM USER_SUBMISSIONS
GROUP BY 1, 2
),
USERS_RANK AS (
SELECT DAILY,
USERNAME,
CORRECT_SUBMISSIONS,
DENSE_RANK() OVER(PARTITION BY DAILY ORDER BY CORRECT_SUBMISSIONS DESC) AS RANK
FROM DAILY_SUBMISSIONS
)
SELECT
DAILY,
USERNAME,
CORRECT_SUBMISSIONS,
RANK
FROM USERS_RANK
WHERE RANK <=3;

--Q4. Find the Top 5 Users with the Highest Number of Incorrect Submissions.

SELECT USERNAME,
SUM(CASE WHEN POINTS < 0 THEN 1 ELSE 0 END) AS INCORRECT_SUBMISSIONS
SUM(POINTS) AS POINTS_EARNED
FROM USER_SUBMISSIONS
GROUP BY 1
ORDER BY INCORRECT_SUBMISSIONS DESC
LIMIT 5;

--Q5. Find the Top 10 Performers for Each Week.

SELECT * FROM (
SELECT
EXTRACT(WEEK FROM SUBMITTED_AT) AS WEEK_NUMBER,
USERNAME,
SUM(POINTS) AS TOTAL_POINTS_EARNED,
DENSE_RANK() OVER(PARTITION BY EXTRACT(WEEK FROM SUBMITTED_AT) ORDER BY SUM(POINTS) DESC) AS RANK
FROM USER_SUBMISSIONS
GROUP BY 1, 2
ORDER BY
WEEK_NUMBER, TOTAL_POINTS_EARNED DESC
)
WHERE RANK <= 10;

----------------------------------------------
------------------THANK YOU-------------------
----------------------------------------------